# HTML
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- deploy_production

# no PR triggers
pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DeleteFiles@1
  name: Delete_Git_Folder
  inputs:
    SourceFolder: '.git'
    Contents: '*'
    RemoveSourceFolder: true

- task: ArchiveFiles@2
  name: Create_Zip
  inputs:
    rootFolderOrFile: '$(build.sourcesDirectory)'
    includeRootFolder: false
- task: PublishBuildArtifacts@1
- task: TriggerPipeline@1
  inputs:
    serviceConnection: 'covidtrigger'
    project: 'CDT.GO.COVID19CAGOV.Website'
    Pipeline: 'Build'
    buildDefinition: 'New-Purge-CDT.GO.COVID19CAGOV.Website'
    Branch: 'master'

 
