name: Eleventy PR Validation
on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Build
        uses: cagov/actions-eleventy@3.1
        with:	
          build_task: build
          build_eleventy_args: --formats=html,njk --input ./pages --output ./docs	
