name: Eleventy Build Master
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'pages/_data/wp/syncmanifest.json'
      
jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: n1hility/cancel-previous-runs@v2
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: cagov/actions-eleventy@2.1
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./docs
          publish_branch: deploy_production
